### ISSUE TITLE
A little question about the code

### ISSUE THREAD

**Issue by CodeLHY** [erikwijmans/Pointnet2_PyTorch#97]
hi @erikwijmans ,

I'm sorry to bother you. Why in class "PointNet2ClassificationSSG", the function "configure_optimizers" uses "self.hparams.batch_size" and "self.hparams.optimizer.decay_step" etc, instead of "self.hparams.task.batch_size" and "self.hparams.task.optimizer.decay_step" etc?

**Comment by erikwijmans** [comment]
That made more sense to me.

**Comment by CodeLHY** [comment]
I'm sorry, my English is not so good, I can't understand the exact meaning of your reply. Hoping that you can help me out.  T.T

**Comment by erikwijmans** [comment]
I decided to not put those fields under `task` as it made more sense to me  -- that way you can override batch size like `batch_size=<blah>` instead of `task.batch_size=<blah>`.  All `task=cls` does is tell hydra to compose in the `task/cls.yaml` file.  It doesn't force everything in that file to be under `task`.

**Comment by CodeLHY** [comment]
Thank you so much. I wish you a smooth work and also have fun every day. 谢谢您！
